### ISSUE TITLE
Create a `file-transfer-persistence` folder in the `example` folder;

### ISSUE THREAD

**Issue by paulocabrita-ionos** [Digital-Ecosystems/edc-ionos-s3#41]
The example should consider the following:
- base on the `file-transfer-push`;
- usage of PostgreSQL container for simplicity;
- before the `step 4`, one connector must be killed, restarted and it should function as normal after the restart;
- the actions of the previous step has to be documented on the MD file;

**Comment by paulocabrita-ionos** [comment]
Please do the following:
- Change the title to `File transfer using push method` to `File transfer using push method - with persistency`;
- Change the item 4 to `Crashing an EDC` and do this:
  - Put this sentence: Let's simulate a crash of a connector.
  - Put the instruction for stopping the provider;
  - Do a select of a table and put the instruction and the result. The idea is to point to a result of a previous curl result;
  - Put the instruction for starting the provider;
  - Put this sentence: Let's resume the file transfer process.

**Comment by darashev-daiteap** [comment]
I have made the changes https://github.com/Digital-Ecosystems/edc-ionos-s3/pull/43/commits/182dd67b67b04ccd5c364a3577683d14f74304d5
